#development
FROM node:22.14.0 as dev

#define working dir
WORKDIR /app

#copy package.json and package-lock.json to container
COPY ./package*.json ./
RUN npm install

#copy all filess
COPY . .

#start app in dev
CMD ["npm", "start"]



