services:
  mongo:
    image: mongo:latest
    restart: unless-stopped
    volumes:
      - kaput-data:/data/db

  backend:
    image: davidgucci/spletno-backend-dev:prod
    restart: unless-stopped
    env_file:
      - ./backend/.env
    depends_on:
      - mongo
    ports:
      - "5000:5000"

  frontend:
    image: davidgucci/spletno-frontend-dev:prod
    restart: unless-stopped
    env_file:
      - ./frontend/.env
    depends_on:
      - backend
    ports:
      - "3000:3000"

  caddy:
    image: caddy:2-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - caddy_data:/data
      - caddy_config:/config
      - ./Caddyfile:/etc/caddy/caddyFile
    depends_on:
      - frontend
      - backend
    restart: unless-stopped

volumes:
  kaput-data:
  caddy_data:
  caddy_config: