# development
FROM node:22 as dev

WORKDIR /app

# Copy only package.json and lock first (for caching)
COPY ./package*.json ./

# Install dependencies
RUN npm install

# Copy the actual app source
COPY . .

# Start the app using nodemon
CMD ["npm", "run", "dev"]

